import React from "react";

import { Metadata } from "next";

export const metadata: Metadata = {
  title:
    "Contact Zerro | Connect with Australia's Fast-Growing Technology Company forInnovative Solutions",
  description: "Generated by create next app",
};

interface LayoutProps {
  children: React.ReactNode;
}

const Layout: React.FC<LayoutProps> = ({ children }) => {
  return <>{children}</>;
};

export default Layout;
