import type { Metadata } from "next";
import { Inter } from "next/font/google";
import MaxWidthContainer from "@/components/common/MaxWidthContainer";
import Navbar from "@/components/common/navbar/Navbar";
import Footer from "@/components/common/Footer";
import ScrollReveal from "@/components/common/ScrollReveal";

import "./globals.css";
import "./icons.css";
import "@/public/icons.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Zerro",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <MaxWidthContainer>{children}</MaxWidthContainer>
        <ScrollReveal>
          <Footer />
        </ScrollReveal>
      </body>
    </html>
  );
}
